services:
  web:
    build: .
    container_name: "alfacycling.com"
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/alfacycling.com
      - /usr/src/app/alfacycling.com/node_modules
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: "mysql"
    restart: always
    env_file:
      - mysql-variables.env
